// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppInfo():Promise<main.AppInfo>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;
