// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}
