// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOssutilInstalled() {
  return window['go']['main']['OSSService']['CheckOssutilInstalled']();
}

export function CreateFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['CreateFile'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['CreateFolder'](arg1, arg2, arg3, arg4);
}

export function DeleteObject(arg1, arg2, arg3) {
  return window['go']['main']['OSSService']['DeleteObject'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['OSSService']['DeleteProfile'](arg1);
}

export function DownloadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['DownloadFile'](arg1, arg2, arg3, arg4);
}

export function EnqueueDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['OSSService']['EnqueueDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function EnqueueDownloadFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['EnqueueDownloadFolder'](arg1, arg2, arg3, arg4);
}

export function EnqueueUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['EnqueueUpload'](arg1, arg2, arg3, arg4);
}

export function EnqueueUploadPaths(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['EnqueueUploadPaths'](arg1, arg2, arg3, arg4);
}

export function GetDefaultProfile() {
  return window['go']['main']['OSSService']['GetDefaultProfile']();
}

export function GetObjectText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['GetObjectText'](arg1, arg2, arg3, arg4);
}

export function GetOssutilPath() {
  return window['go']['main']['OSSService']['GetOssutilPath']();
}

export function GetProfile(arg1) {
  return window['go']['main']['OSSService']['GetProfile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['OSSService']['GetSettings']();
}

export function GetTransferHistory() {
  return window['go']['main']['OSSService']['GetTransferHistory']();
}

export function ListBuckets(arg1) {
  return window['go']['main']['OSSService']['ListBuckets'](arg1);
}

export function ListObjects(arg1, arg2, arg3) {
  return window['go']['main']['OSSService']['ListObjects'](arg1, arg2, arg3);
}

export function ListObjectsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['OSSService']['ListObjectsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadProfiles() {
  return window['go']['main']['OSSService']['LoadProfiles']();
}

export function MoveObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['OSSService']['MoveObject'](arg1, arg2, arg3, arg4, arg5);
}

export function PresignObject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['PresignObject'](arg1, arg2, arg3, arg4);
}

export function PutObjectText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['PutObjectText'](arg1, arg2, arg3, arg4);
}

export function SaveProfile(arg1) {
  return window['go']['main']['OSSService']['SaveProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['OSSService']['SaveSettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['OSSService']['SetContext'](arg1);
}

export function SetOssutilPath(arg1) {
  return window['go']['main']['OSSService']['SetOssutilPath'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['OSSService']['TestConnection'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['UploadFile'](arg1, arg2, arg3, arg4);
}
