// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOssutilInstalled() {
  return window['go']['main']['OSSService']['CheckOssutilInstalled']();
}

export function DeleteObject(arg1, arg2, arg3) {
  return window['go']['main']['OSSService']['DeleteObject'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['OSSService']['DeleteProfile'](arg1);
}

export function DownloadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['DownloadFile'](arg1, arg2, arg3, arg4);
}

export function GetDefaultProfile() {
  return window['go']['main']['OSSService']['GetDefaultProfile']();
}

export function GetOssutilPath() {
  return window['go']['main']['OSSService']['GetOssutilPath']();
}

export function GetProfile(arg1) {
  return window['go']['main']['OSSService']['GetProfile'](arg1);
}

export function ListBuckets(arg1) {
  return window['go']['main']['OSSService']['ListBuckets'](arg1);
}

export function ListObjects(arg1, arg2, arg3) {
  return window['go']['main']['OSSService']['ListObjects'](arg1, arg2, arg3);
}

export function LoadProfiles() {
  return window['go']['main']['OSSService']['LoadProfiles']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['OSSService']['SaveProfile'](arg1);
}

export function SetOssutilPath(arg1) {
  return window['go']['main']['OSSService']['SetOssutilPath'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['OSSService']['TestConnection'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['OSSService']['UploadFile'](arg1, arg2, arg3, arg4);
}
