// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckOssutilInstalled():Promise<main.ConnectionResult>;

export function DeleteObject(arg1:main.OSSConfig,arg2:string,arg3:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DownloadFile(arg1:main.OSSConfig,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetDefaultProfile():Promise<main.OSSProfile>;

export function GetObjectText(arg1:main.OSSConfig,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetOssutilPath():Promise<string>;

export function GetProfile(arg1:string):Promise<main.OSSProfile>;

export function GetSettings():Promise<main.AppSettings>;

export function ListBuckets(arg1:main.OSSConfig):Promise<Array<main.BucketInfo>>;

export function ListObjects(arg1:main.OSSConfig,arg2:string,arg3:string):Promise<Array<main.ObjectInfo>>;

export function LoadProfiles():Promise<Array<main.OSSProfile>>;

export function PresignObject(arg1:main.OSSConfig,arg2:string,arg3:string,arg4:string):Promise<string>;

export function PutObjectText(arg1:main.OSSConfig,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveProfile(arg1:main.OSSProfile):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SetOssutilPath(arg1:string):Promise<void>;

export function TestConnection(arg1:main.OSSConfig):Promise<main.ConnectionResult>;

export function UploadFile(arg1:main.OSSConfig,arg2:string,arg3:string,arg4:string):Promise<void>;
